### ISSUE TITLE
db:seed is not working

### ISSUE THREAD

**Issue by davelooi** [sebpearce/expenses#2]
https://github.com/sebpearce/expenses/pull/3

**Comment by sebpearce** [comment]
Cheers – I'd just changed a field in the model last night but haven't gotten around to updating this yet.

**Comment by davelooi** [comment]
While I understand why you made those changes. There are better ways to do it. https://github.com/sebpearce/expenses/pull/3

However, these exposes some design issues. We'll chat in detail tomorrow with a white board.
